SELECT * FROM ADDRESS;

SELECT * FROM STYDU;

SELECT SURNAME,NAME,MIDDLE_NAME FROM PATIENT WHERE ID IN
	(SELECT ID FROM ADDRESS WHERE COUNTRY='Russia');

SELECT PATIENT.SURNAME,PATIENT.NAME,ADDRESS.COUNTRY,ADDRESS.CITY,ADDRESS.HOUSE,PATIENT.APARTMENT 
	FROM PATIENT LEFT OUTER JOIN ADDRESS
		ON PATIENT.ID_ADDRESS=ADDRESS.ID;

SELECT SUBDIVISION.NAME,ADDRESS.COUNTRY,ADDRESS.CITY,ADDRESS.STREET,ADDRESS.HOUSE	
	FROM SUBDIVISION LEFT OUTER JOIN ADDRESS
		ON SUBDIVISION.ID_ADDRESS = ADDRESS.ID;

SELECT PATIENT.SURNAME,PATIENT.NAME,VISIT.STATUS_VISIT,VISIT.VISIT_DATE 
	FROM PATIENT LEFT OUTER JOIN VISIT
		ON PATIENT.ID=VISIT.ID_PATIENT;

SELECT STYDU.EXPIRATION_DATE,STYDU.STATUS, RESEARCH_DIRECTORY.NAME,RESEARCH_DIRECTORY.COST,RESEARCH_DIRECTORY.DURATION
	FROM STYDU LEFT OUTER JOIN RESEARCH_DIRECTORY
		ON STYDU.ID_RESEARCH_DIRECTORY = RESEARCH_DIRECTORY.ID;

SELECT VISIT.STATUS_VISIT,VISIT.VISIT_DATE,STYDU.EXPIRATION_DATE,STYDU.STATUS 
	FROM VISIT RIGHT OUTER JOIN STYDU
		ON VISIT.ID=STYDU.ID_VISIT;

SELECT 	PATIENT.NAME, 
	PATIENT.SURNAME,
	VISIT.VISIT_DATE, 
	VISIT.STATUS_VISIT,
	STYDU.STATUS
FROM	PATIENT,
	VISIT,
	STYDU
		
WHERE ((PATIENT.ID = VISIT.ID_PATIENT) AND (VISIT.ID = STYDU.ID_VISIT));

SELECT 	PATIENT.NAME, 
	PATIENT.SURNAME,
	ADDRESS.COUNTRY,
	ADDRESS.CITY,
	ADDRESS.HOUSE,
	SUBDIVISION.NAME
FROM	PATIENT,
	ADDRESS,
	SUBDIVISION
		
WHERE ((PATIENT.ID_ADDRESS = ADDRESS.ID) AND (ADDRESS.ID = SUBDIVISION.ID_ADDRESS));